## This file constructs the fourth plot in the project, named plot4.png  
library(datasets)
##opens png device (default width is 480 pixels and default height is 480 pixels)
png(filename="plot4.png") 
##reads the data (only the 2 dates)
dt<-read.csv2("household_power_consumption.txt",na.strings=c("?"), skip=66636,nrows=2880, colClasses="character")
temp<-read.csv2("household_power_consumption.txt",nrows=1)
names(dt)<-names(temp)
## converts the Date and Time variables to Date/Time classes (creates a new variable including both)
dt$Date<-as.Date(dt$Date, "%d/%m/%Y")
dt$Time1<-paste(dt$Date, dt$Time)
dt$Time1<-strptime(dt$Time1,format= "%Y-%m-%d %H:%M:%S")
## constructs the plot with required lables, titles and legend 
par(mfrow=c(2,2))
plot(dt$Time1,as.numeric(dt$Sub_metering_1),type="l",ylab="Energy sub metering",xlab="")
plot(dt$Time1,as.numeric(dt$Global_active_power),type="l",ylab="Global Active Power (kilowatts)",xlab="")
par(mfrow=c(2,2))
plot(dt$Time1,as.numeric(dt$Global_active_power),type="l",ylab="Global Active Power (kilowatts)",xlab="")
plot(dt$Time1,as.numeric(dt$Voltage),type="l",ylab="Voltage",xlab="datetime")
plot(dt$Time1,as.numeric(dt$Sub_metering_1),type="l",ylab="Energy sub metering",xlab="")
with(dt, lines(dt$Time1,as.numeric(dt$Sub_metering_2),col="red"))
with(dt, lines(dt$Time1,as.numeric(dt$Sub_metering_3),col="blue"))
legend("topright",lty=c(1,1),col=c("black","red","blue"), legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),  bty="n")
plot(dt$Time1,as.numeric(dt$Global_reactive_power),type="l",ylab="Global_reactive_power",xlab="datetime")
dev.off()
